name: Sync Repos

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --global user.email "mcdulltii@gmail.com"
          git config --global user.name "mcdulltii"
          git clone https://${{ secrets.PAT }}@github.com/inf2007/inf2007-team25-2024.git
          git clone https://${{ secrets.PAT }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          cd inf2007-team25-2024
          cp ../${{ env.ORIGINAL_REPO_NAME }}/* . -rf
          git add .
          git commit -m "Sync from source"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: mcdulltii
