name: Unit Tests

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test-feature:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run gradle wrapper
        run: gradle wrapper
      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew
      - name: Run Tests with Gradle
        id: test
        run: |
          ./gradlew test
          echo "::set-output name=test-passed::true"
      - name: Test Result
        if: steps.test.outputs.test-passed == 'true'
        run: echo "Unit tests passed!"
